// Central business / brand constants
export const SITE = {
  name: "WebDesignFLA",
  brand: "WebDesignFLA",
  tagline: "Website Design, Development & Marketing Agency in Jupiter, FL",
  phoneDisplay: "(561) 464-6222",
  phoneHref: "tel:+15614646222",
  email: "admin@webdesignfla.com",
  addressLine1: "103 South U.S. Hwy 1",
  addressLine2: "Jupiter, FL 33477",
  city: "Jupiter",
  state: "FL",
  zip: "33477",
  url: "https://webdesignfla.com",
  founded: 2010,
  stats: {
    satisfied: 639,
    active: 303,
    statesServed: 48,
    avgYears: 12,
  },
};

export const NAV_LINKS = [
  { label: "Home", to: "/" },
  { label: "Web Design", to: "/web-design/" },
  { label: "SEO", to: "/seo/" },
  { label: "Social Media", to: "/social/" },
  { label: "Portfolio", to: "/portfolio/" },
];

export const PORTFOLIO_ITEMS = [
  { title: "Commercial Building Services", img: "/portfolio/commercial.jpg", category: "Web Design" },
  { title: "Stall Savers", img: "/portfolio/StallSavers.jpg", category: "Web Design" },
  { title: "Addicted 2 Italy", img: "/portfolio/addicted2Itely.jpg", category: "Web Design" },
  { title: "Ariel Homes", img: "/portfolio/arielhomes.jpg", category: "Web Design" },
  { title: "Integrity Garage Door Services", img: "/portfolio/integrity.jpg", category: "Web Design" },
  { title: "Oceans Treasure", img: "/portfolio/OceansTreasure.jpg", category: "Web Design" },
  { title: "Integrated Cable Solutions", img: "/portfolio/IntegratedCable.jpg", category: "Web Design" },
  { title: "Smith Fence", img: "/portfolio/SmithFence.jpg", category: "Web Design" },
  { title: "Okeefe's Tavern", img: "/portfolio/Okeefe.jpg", category: "Web Design" },
  { title: "Florida Tech Law", img: "/portfolio/fllawtech.jpg", category: "Web Design" },
  { title: "Clear-Tech Pools", img: "/portfolio/ClearTech.jpg", category: "Web Design" },
  { title: "Childcare Of Brandon", img: "/portfolio/childcareofbrandon.jpg", category: "Web Design" },
  { title: "Inject-A-Deck", img: "/portfolio/injectadeck.jpg", category: "Web Design" },
  { title: "Trident H2O", img: "/portfolio/skywaterpools.jpg", category: "Web Design" },
  { title: "Upper Room", img: "/portfolio/billahrens.jpg", category: "Web Design" },
  { title: "Oasis Climatic", img: "/portfolio/oasisclimaticus.jpg", category: "Web Design" },
  { title: "Sky Water Pools", img: "/portfolio/tridenth2o.jpg", category: "Web Design" },
  { title: "Upperroom Studio", img: "/portfolio/upperroom.jpg", category: "Web Design" },
  { title: "Superior Auto Loans", img: "/portfolio/superiorautoloans.jpg", category: "Web Design" },
  { title: "Mickey's Peanuts", img: "/portfolio/mickeyspeanut.jpg", category: "Web Design" },
  { title: "JetBrite", img: "/portfolio/jetbrite.jpg", category: "Web Design" },
  { title: "How The Mind Works", img: "/portfolio/mindworks.jpg", category: "Web Design" },
  { title: "Florida Covered Storage", img: "/portfolio/coveredstorage.jpg", category: "Web Design" },
  { title: "Michael's Pool Service", img: "/portfolio/mikepool.jpg", category: "Web Design" },
  { title: "Dynatherm", img: "/portfolio/dynatherm.jpg", category: "Web Design" },
  { title: "Compass Limo", img: "/portfolio/compass.jpg", category: "Web Design" },
  { title: "Clearwater Tub And Tile Refinishing", img: "/portfolio/clearwater.jpg", category: "Web Design" },
  { title: "Backyard Pool Service", img: "/portfolio/backyard.jpg", category: "Web Design" },
  { title: "7 Springs Self Storage", img: "/portfolio/7springs.jpg", category: "Web Design" },
  { title: "Upperroom Recording", img: "/portfolio/popey.jpg", category: "Web Design" },
];
